### ISSUE TITLE
Hide `Regex` needle by feature and enable it by default

### ISSUE THREAD

**Issue by zhiburt** [zhiburt/expectrl#37]
I think for people who don't uses Regex, it could be good to not include it as a dependency to decrease a crate size.

```toml
[features]
default = ["regex"]
regex = ["regex"]
```

So it could be used like this.

```toml
expectrl = { version = "0.0.1", default-features = false }
```
